name: CI

on:
  push:
    tags: ["v*"]
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  bundle:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [16.x]
        experimental: [false]
        include:
          - node: 18.x
            os: ubuntu-latest
            experimental: false
          - node: 18.x
            os: macos-latest
            experimental: false
          - node: 18.x
            os: windows-latest
            experimental: false
        
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      - name: Lint src
        run: npm run lint
      - name: Bundle
        run: npm run bundle

  publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: bundle
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm install
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
